version: '0.5'

services:
  sbc_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - sbc_backend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  sbc_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      sbc_postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@sbc_postgres:5432/creditScoreDB
      # - MONGO_URL=mongodb://mongo:27017/mydatabase
    volumes:
      - ./backend:/app
    #command: >
    #  sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  sbc_postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: creditScoreDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      retries: 5

#  mongo:
#    image: mongo:6
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db

volumes:
  postgres_data:
  #mongo_data:
