"""create customers table

Revision ID: e95a95450115
Revises: 1da69727b56d
Create Date: 2025-04-11 20:21:58.256604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95a95450115'
down_revision: Union[str, None] = '1da69727b56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('monthly_inhand_salary', sa.Float(), nullable=True),
    sa.Column('num_bank_accounts', sa.Integer(), nullable=True),
    sa.Column('num_credit_cards', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.Column('num_of_loan', sa.Integer(), nullable=True),
    sa.Column('delay_from_due_date', sa.Integer(), nullable=True),
    sa.Column('num_of_delayed_payment', sa.Float(), nullable=True),
    sa.Column('changed_credit_limit', sa.Float(), nullable=True),
    sa.Column('num_credit_inquiries', sa.Integer(), nullable=True),
    sa.Column('credit_mix', sa.String(), nullable=True),
    sa.Column('outstanding_debt', sa.Float(), nullable=True),
    sa.Column('credit_utilization_ratio', sa.Float(), nullable=True),
    sa.Column('credit_history_age', sa.Integer(), nullable=True),
    sa.Column('payment_of_min_amount', sa.String(), nullable=True),
    sa.Column('total_emi_per_month', sa.Float(), nullable=True),
    sa.Column('amount_invested_monthly', sa.Float(), nullable=True),
    sa.Column('payment_behaviour', sa.String(), nullable=True),
    sa.Column('monthly_balance', sa.Float(), nullable=True),
    sa.Column('last_loan_9', sa.String(), nullable=True),
    sa.Column('last_loan_8', sa.String(), nullable=True),
    sa.Column('last_loan_7', sa.String(), nullable=True),
    sa.Column('last_loan_6', sa.String(), nullable=True),
    sa.Column('last_loan_5', sa.String(), nullable=True),
    sa.Column('last_loan_4', sa.String(), nullable=True),
    sa.Column('last_loan_3', sa.String(), nullable=True),
    sa.Column('last_loan_2', sa.String(), nullable=True),
    sa.Column('last_loan_1', sa.String(), nullable=True),
    sa.Column('credit_score', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_table('customers')
    # ### end Alembic commands ###
