"""Initial migration

Revision ID: fef991ad4dc0
Revises: 
Create Date: 2025-03-07 05:01:21.544124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef991ad4dc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('ocupacion', sa.String(), nullable=True),
    sa.Column('meses_trabajando', sa.Integer(), nullable=True),
    sa.Column('salario_mensual', sa.Float(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('cedula')
    )
    op.create_index(op.f('ix_clientes_cedula'), 'clientes', ['cedula'], unique=False)
    op.create_table('creditos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('deuda_total', sa.Float(), nullable=True),
    sa.Column('cuota_mensual', sa.Float(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('tipo_deuda', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cedula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditos_id'), 'creditos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creditos_id'), table_name='creditos')
    op.drop_table('creditos')
    op.drop_index(op.f('ix_clientes_cedula'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
