services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []
  
  #frontend:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.frontend
  #  ports:
  #    - "3000:3000"